from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, TIMESTAMP

Base = declarative_base()

class BomRecord(Base):
    __tablename__ = 'table_bom'

    id = Column(Integer, primary_key=True, index=True)  # Coluna de ID única
    plan_date = Column(name="plan_date", type_=TIMESTAMP)
    top_item = Column(name="top item", type_=String)
    top_desc = Column(name="top desc", type_=String)
    level = Column(name="level", type_=String)
    parent_item = Column(name="parent item", type_=String)
    parent_uit = Column(name="parent uit", type_=String)
    child_item = Column(name="child item", type_=String)
    child_desc = Column(name="child desc", type_=String)
    child_spec = Column(name="child spec", type_=String)
    child_uit = Column(name="child uit", type_=String)
    child_rev = Column(name="child rev", type_=String)
    supply_type = Column(name="supply type", type_=String)
    child_c_osp = Column(name="child c osp", type_=String)
    make_buy = Column(name="make buy", type_=String)
    desig_no = Column(name="desig no", type_=String)
    eco_no = Column(name="eco no", type_=String)
    quantity = Column(name="quantity", type_=String)
    extended_quantity = Column(name="extended quantity", type_=String)
    start_date = Column(name="start date", type_=String)
    end_date = Column(name="end date", type_=String)
    org = Column(name="org", type_=String)
    comments = Column(name="comments", type_=String)
    subs_item_1 = Column(name="subs item 1", type_=String)
    subs_item_2 = Column(name="subs item 2", type_=String)
    subs_item_3 = Column(name="subs item 3", type_=String)
    subs_item_4 = Column(name="subs item 4", type_=String)
    subs_item_5 = Column(name="subs item 5", type_=String)
    subs_item_6 = Column(name="subs item 6", type_=String)
    subs_item_7 = Column(name="subs item 7", type_=String)
    subs_item_8 = Column(name="subs item 8", type_=String)
    subs_item_9 = Column(name="subs item 9", type_=String)
    qpa = Column(name="qpa", type_=String)
    class_code = Column(name="class code", type_=String)
    class_name = Column(name="class name", type_=String)
    uom = Column(name="uom", type_=String)
    svc_code = Column(name="svc code", type_=String)
    svc_location = Column(name="svc location", type_=String)
    code = Column(name="code", type_=String)
    code2 = Column(name="code2", type_=String)
    local = Column(name="local", type_=String)
    assy = Column(name="assy", type_=String)
    supplier = Column(name="supplier", type_=String)
    line = Column(name="line", type_=String)
    planner = Column(name="planner", type_=String)
    purchaser = Column(name="purchaser", type_=String)
    supplier_name = Column(name="supplier name", type_=String)
    model_mrp = Column(name="model mrp", type_=String)
